

[
    {
        "domain": ".linkedin.com",
        "hostOnly": false,
        "httpOnly": false,
        "name": "s_ips",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": true,
        "storeId": null,
        "value": "735"
    },
    {
        "domain": ".linkedin.com",
        "expirationDate": 1642003417.646232,
        "hostOnly": false,
        "httpOnly": false,
        "name": "lms_ads",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "AQFCnJJ02l9pdwAAAX20iQH19OnYEYkPlcRBjpw4nScODmpAv-EUEEdSuCg7rZBF2Y-5ZyvCEcrGebk_qu_AponGNH9tlX3f"
    },
    {
        "domain": ".www.linkedin.com",
        "expirationDate": 1698891136,
        "hostOnly": false,
        "httpOnly": false,
        "name": "G_ENABLED_IDPS",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "google"
    },
    {
        "domain": ".linkedin.com",
        "expirationDate": 1699425190.613252,
        "hostOnly": false,
        "httpOnly": false,
        "name": "bcookie",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "\"v=2&f52dbf3e-d957-4211-8521-a38df413c6ff\""
    },
    {
        "domain": ".linkedin.com",
        "expirationDate": 1647305137,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_gcl_au",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "1.1.964356063.1631244632"
    },
    {
        "domain": ".linkedin.com",
        "expirationDate": 1642003417.646298,
        "hostOnly": false,
        "httpOnly": false,
        "name": "lms_analytics",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "AQFCnJJ02l9pdwAAAX20iQH19OnYEYkPlcRBjpw4nScODmpAv-EUEEdSuCg7rZBF2Y-5ZyvCEcrGebk_qu_AponGNH9tlX3f"
    },
    {
        "domain": ".linkedin.com",
        "hostOnly": false,
        "httpOnly": false,
        "name": "AMCVS_14215E3D5995C57C0A495C55%40AdobeOrg",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": true,
        "storeId": null,
        "value": "1"
    },
    {
        "domain": ".www.linkedin.com",
        "expirationDate": 1670556124.816375,
        "hostOnly": false,
        "httpOnly": true,
        "name": "li_at",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "AQEDATeVhtsC7EqrAAABfN5rX9MAAAF9wULd0k0AtK4jT_ilxmgnIP0DFmD87Te-Qahbt4oEn6ILUTLlyjZGC9mY8X-flpkdlHO75UPVVj0eKkUqJa3fMDYkx4fuoSLM4qYL9PFcvka39iDMKaIlUj2v"
    },
    {
        "domain": ".linkedin.com",
        "hostOnly": false,
        "httpOnly": false,
        "name": "lang",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": true,
        "storeId": null,
        "value": "v=2&lang=en-us"
    },
    {
        "domain": ".linkedin.com",
        "hostOnly": false,
        "httpOnly": false,
        "name": "at_check",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": true,
        "storeId": null,
        "value": "true"
    },
    {
        "domain": ".linkedin.com",
        "expirationDate": 1639619315.271159,
        "hostOnly": false,
        "httpOnly": false,
        "name": "lidc",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "\"b=OB67:s=O:r=O:a=O:p=O:g=2449:u=13:x=1:i=1639532914:t=1639619314:v=2:sig=AQHKqOwn13_fGZVmfZupw939Gr4F3VID\""
    },
    {
        "domain": ".linkedin.com",
        "expirationDate": 1655004697,
        "hostOnly": false,
        "httpOnly": false,
        "name": "gpv_pn",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "developer.linkedin.com%2F"
    },
    {
        "domain": ".linkedin.com",
        "expirationDate": 1694671137,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_ga",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "GA1.2.25982272.1631598918"
    },
    {
        "domain": ".linkedin.com",
        "expirationDate": 1639987641,
        "hostOnly": false,
        "httpOnly": false,
        "name": "aam_uuid",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "10727254536107636614444051152443066182"
    },
    {
        "domain": ".linkedin.com",
        "expirationDate": 1655081137,
        "hostOnly": false,
        "httpOnly": false,
        "name": "AMCV_14215E3D5995C57C0A495C55%40AdobeOrg",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "-637568504%7CMCIDTS%7C18977%7CMCMID%7C10212540312662646464423484567277155469%7CMCAAMLH-1638000293%7C3%7CMCAAMB-1639529136%7CRKhpRz8krg2tLO6pguXWp5olkAcUniQYPHaMWWgdJ3xzPWQmdj0y%7CMCOPTOUT-1639536337s%7CNONE%7CvVersion%7C5.1.1%7CMCCIDH%7C1275415199"
    },
    {
        "domain": ".linkedin.com",
        "expirationDate": 1642003417.167604,
        "hostOnly": false,
        "httpOnly": false,
        "name": "AnalyticsSyncHistory",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "AQJhMJZXxqDj6gAAAX20iP_qjVUlejkUqKxvC2pHRno3wlU9unG49s02qJbQB9j5N6ugVFqgfnjqPy3FqNG3lg"
    },
    {
        "domain": ".www.linkedin.com",
        "expirationDate": 1699425190.613323,
        "hostOnly": false,
        "httpOnly": true,
        "name": "bscookie",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "\"v=1&20211107185537dd6dcb05-e954-41fa-8fc5-2a948f579d0bAQHyTiV_-XFOTUekOu_UQ4GvfQte_Vcx\""
    },
    {
        "domain": ".www.linkedin.com",
        "expirationDate": 1670556124.816564,
        "hostOnly": false,
        "httpOnly": false,
        "name": "JSESSIONID",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "\"ajax:8901034187216829116\""
    },
    {
        "domain": ".www.linkedin.com",
        "expirationDate": 1662780654.532978,
        "hostOnly": false,
        "httpOnly": true,
        "name": "li_rm",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "AQHStbPAWW9P_AAAAXvNwheDw4Dd8BsO0aG5i3fsI3hqE4jyAZNGc4t1Epb6mOecDeQBZxfRnMso8aXppH6wcVbLRC1DAG0uSlhhtJs_8KtVqrx_VLhye_nh"
    },
    {
        "domain": ".linkedin.com",
        "expirationDate": 1647308914.46681,
        "hostOnly": false,
        "httpOnly": false,
        "name": "li_sugr",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "2ad872fd-cd98-48ef-8832-d945a84add19"
    },
    {
        "domain": ".linkedin.com",
        "expirationDate": 1670556124.816505,
        "hostOnly": false,
        "httpOnly": false,
        "name": "liap",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "true"
    },
    {
        "domain": ".linkedin.com",
        "hostOnly": false,
        "httpOnly": false,
        "name": "s_cc",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": true,
        "storeId": null,
        "value": "true"
    },
    {
        "domain": ".linkedin.com",
        "expirationDate": 1655004697,
        "hostOnly": false,
        "httpOnly": false,
        "name": "s_fid",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "731B4558830707A5-0A974DE565086121"
    },
    {
        "domain": ".linkedin.com",
        "hostOnly": false,
        "httpOnly": false,
        "name": "s_plt",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": true,
        "storeId": null,
        "value": "1.10"
    },
    {
        "domain": ".linkedin.com",
        "hostOnly": false,
        "httpOnly": false,
        "name": "s_pltp",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": true,
        "storeId": null,
        "value": "developer.linkedin.com%2F"
    },
    {
        "domain": ".linkedin.com",
        "hostOnly": false,
        "httpOnly": false,
        "name": "s_ppv",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": true,
        "storeId": null,
        "value": "developer.linkedin.com%2F%2C30%2C30%2C735%2C1%2C3"
    },
    {
        "domain": ".linkedin.com",
        "hostOnly": false,
        "httpOnly": false,
        "name": "s_tp",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": true,
        "storeId": null,
        "value": "2484"
    },
    {
        "domain": ".linkedin.com",
        "expirationDate": 1655004697,
        "hostOnly": false,
        "httpOnly": false,
        "name": "s_tslv",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "1639452697223"
    },
    {
        "domain": ".linkedin.com",
        "hostOnly": false,
        "httpOnly": false,
        "name": "sdsc",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": true,
        "storeId": null,
        "value": "1%3A1SZM1shxDNbLt36wZwCgPgvN58iw%3D"
    },
    {
        "domain": ".www.linkedin.com",
        "expirationDate": 1640742511,
        "hostOnly": false,
        "httpOnly": false,
        "name": "timezone",
        "path": "/",
        "sameSite": null,
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "Asia/Colombo"
    },
    {
        "domain": ".linkedin.com",
        "expirationDate": 1642124914,
        "hostOnly": false,
        "httpOnly": false,
        "name": "UserMatchHistory",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "AQIVDjWfmm2WgwAAAX27xuH18M16iC2f-ylwKGgvQRBdt-O17vnnD3HB2WM7U_QlFaM0G_20XvlOtWPQ502wjLbHiv7T_XaQqL85HvLbsRlQ_Hwo4RoqBCNJAU989O9a9GLET1jqG_5EJ5J2crvkTGrFOOvu_ELF5FLdJ160nppId6vyHNJnEQWJs9kyIzeUb2MH8vRt1eQnGi9nxEc4xGSI865G87RzB90cQ4jigYsaMEbd28cwTfQVyVAsiFSL9PoFpRz5n-3qRVyBxFh_j7jfgWNSNcFLmKf_nNE"
    }
] 
